This notebook is written to extracted several features from the text and then the extracted features are used to classify them into the given classes. The implementation is performed using the spam dataset. The participants have to use different datasets given in the Dataset folder and perform the classification.

You have to specify your own path where the code and datasets are present

In [ ]:
import pandas as pd 
data =  pd.read_csv('SMSSpamCollection.csv', sep = '\t', names = ['label', 'message'])
data.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
text = data['message']
label = data['label']

In [ ]:
#Number of Words
#x = lambda a : a + 10
#print(x(5))
data['word_count'] = data['message'].apply(lambda x: len(str(x).split(" ")))
data[['message','word_count']].head()

                                             message  word_count
0  Go until jurong point, crazy.. Available only ...          20
1                      Ok lar... Joking wif u oni...           6
2  Free entry in 2 a wkly comp to win FA Cup fina...          28
3  U dun say so early hor... U c already then say...          11
4  Nah I don't think he goes to usf, he lives aro...          13

In [ ]:
#Number of characters
data['char_count'] = data['message'].str.len() ## this also includes spaces
data[['message','char_count']].head()

                                             message  char_count
0  Go until jurong point, crazy.. Available only ...         111
1                      Ok lar... Joking wif u oni...          29
2  Free entry in 2 a wkly comp to win FA Cup fina...         155
3  U dun say so early hor... U c already then say...          49
4  Nah I don't think he goes to usf, he lives aro...          61

In [ ]:
#Average Word Length
def avg_word(sentence):
  words = sentence.split()
  #print(words)
  return (sum(len(word) for word in words)/len(words))

data['avg_word'] = data['message'].apply(lambda x: avg_word(x))
data[['message','avg_word']].head()

                                             message  avg_word
0  Go until jurong point, crazy.. Available only ...         4
1                      Ok lar... Joking wif u oni...         4
2  Free entry in 2 a wkly comp to win FA Cup fina...         4
3  U dun say so early hor... U c already then say...         3
4  Nah I don't think he goes to usf, he lives aro...         3

In [ ]:
#Number of stopwords
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop = stopwords.words('english')

data['stopwords'] = data['message'].apply(lambda x: len([x for x in x.split() if x in stop]))
data[['message','stopwords']].head()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:7: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  import sys

                                             message  stopwords
0  Go until jurong point, crazy.. Available only ...          4
1                      Ok lar... Joking wif u oni...          0
2  Free entry in 2 a wkly comp to win FA Cup fina...          5
3  U dun say so early hor... U c already then say...          2
4  Nah I don't think he goes to usf, he lives aro...          5

In [ ]:
#Number of special characters
data['hastags'] = data['message'].apply(lambda x: len([x for x in x.split() if x.startswith('#')]))
data[['message','hastags']].head()

                                             message  hastags
0  Go until jurong point, crazy.. Available only ...        0
1                      Ok lar... Joking wif u oni...        0
2  Free entry in 2 a wkly comp to win FA Cup fina...        0
3  U dun say so early hor... U c already then say...        0
4  Nah I don't think he goes to usf, he lives aro...        0

In [ ]:
#Number of numerics
data['numerics'] = data['message'].apply(lambda x: len([x for x in x.split() if x.isdigit()]))
data[['message','numerics']].head()

                                             message  numerics
0  Go until jurong point, crazy.. Available only ...         0
1                      Ok lar... Joking wif u oni...         0
2  Free entry in 2 a wkly comp to win FA Cup fina...         2
3  U dun say so early hor... U c already then say...         0
4  Nah I don't think he goes to usf, he lives aro...         0

In [ ]:
#Number of Uppercase words
data['upper'] = data['message'].apply(lambda x: len([x for x in x.split() if x.isupper()]))
data[['message','upper']].head()

                                             message  upper
0  Go until jurong point, crazy.. Available only ...      0
1                      Ok lar... Joking wif u oni...      0
2  Free entry in 2 a wkly comp to win FA Cup fina...      2
3  U dun say so early hor... U c already then say...      2
4  Nah I don't think he goes to usf, he lives aro...      1

In [ ]:
pos_family = {
    'noun' : ['NN','NNS','NNP','NNPS'],
    'pron' : ['PRP','PRP$','WP','WP$'],
    'verb' : ['VB','VBD','VBG','VBN','VBP','VBZ'],
    'adj' :  ['JJ','JJR','JJS'],
    'adv' : ['RB','RBR','RBS','WRB']
}

# function to check and get the part of speech tag count of a words in a given sentence
from textblob import TextBlob, Word, Blobber
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
def check_pos_tag(x, flag):
    cnt = 0
    try:
        wiki = TextBlob(x)
        for tup in wiki.tags:
            ppo = list(tup)[1]
            if ppo in pos_family[flag]:
                cnt += 1
    except:
        pass
    return cnt

data['noun_count'] = data['message'].apply(lambda x: check_pos_tag(x, 'noun'))
data['verb_count'] = data['message'].apply(lambda x: check_pos_tag(x, 'verb'))
data['adj_count'] = data['message'].apply(lambda x: check_pos_tag(x, 'adj'))
data['adv_count'] = data['message'].apply(lambda x: check_pos_tag(x, 'adv'))
data['pron_count'] = data['message'].apply(lambda x: check_pos_tag(x, 'pron'))
data[['message','noun_count','verb_count','adj_count', 'adv_count', 'pron_count' ]].head()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.

,message,noun_count,verb_count,adj_count,adv_count,pron_count
0,"Go until jurong point, crazy.. Available only ...",9,1,3,3,0
1,Ok lar... Joking wif u oni...,4,1,1,0,0
2,Free entry in 2 a wkly comp to win FA Cup fina...,14,3,4,0,0
3,U dun say so early hor... U c already then say...,3,3,2,3,0
4,"Nah I don't think he goes to usf, he lives aro...",1,5,0,3,3

In [ ]:
data[['message','word_count','char_count','avg_word','stopwords','hastags','numerics','upper','noun_count','verb_count','adj_count', 'adv_count', 'pron_count','label' ]].head()

,message,word_count,char_count,avg_word,stopwords,hastags,numerics,upper,noun_count,verb_count,adj_count,adv_count,pron_count,label
0,"Go until jurong point, crazy.. Available only ...",20,111,4,4,0,0,0,9,1,3,3,0,ham
1,Ok lar... Joking wif u oni...,6,29,4,0,0,0,0,4,1,1,0,0,ham
2,Free entry in 2 a wkly comp to win FA Cup fina...,28,155,4,5,0,2,2,14,3,4,0,0,spam
3,U dun say so early hor... U c already then say...,11,49,3,2,0,0,2,3,3,2,3,0,ham
4,"Nah I don't think he goes to usf, he lives aro...",13,61,3,5,0,0,1,1,5,0,3,3,ham

In [ ]:
features = data[['word_count','char_count','avg_word','stopwords','hastags','numerics','upper','noun_count','verb_count','adj_count', 'adv_count', 'pron_count']]

In [ ]:
#label = data['label']

import numpy as np
classes_list = ["ham","spam"]
label_index = data['label'].apply(classes_list.index)
label = np.asarray(label_index)

In [ ]:
import numpy as np
features_array = np.asarray(features)

In [ ]:
features_array.shape

(5572, 12)

In [ ]:
# data split into train and text
import numpy as np
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(features_array, label, test_size=0.33, random_state=42)

In [ ]:

from sklearn.metrics import accuracy_score
from sklearn import metrics

from sklearn.svm import SVC
model_SVM = SVC()
model_SVM.fit(x_train, y_train)
y_pred_SVM = model_SVM.predict(x_test)
print("SVM")
print("Accuracy score =", accuracy_score(y_test, y_pred_SVM))
print(metrics.classification_report(y_test, y_pred_SVM))

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100,max_depth=None,min_samples_split=2, random_state=0)
rf.fit(x_train,y_train)
y_pred_rf = rf.predict(x_test)
print("random")
print("Accuracy score =", accuracy_score(y_test, y_pred_rf))
print(metrics.classification_report(y_test, y_pred_rf))

from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
LR.fit(x_train,y_train)
y_pred_LR = LR.predict(x_test)
print("Logistic Regression")
print("Accuracy score =", accuracy_score(y_test, y_pred_LR))
print(metrics.classification_report(y_test, y_pred_LR ))

from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors = 5)
neigh.fit(x_train,y_train)
y_pred_KNN = neigh.predict(x_test)
print("KNN")
print("Accuracy score =", accuracy_score(y_test, y_pred_KNN))
print(metrics.classification_report(y_test, y_pred_KNN ))

from sklearn.naive_bayes import GaussianNB
naive = GaussianNB()
naive.fit(x_train,y_train)
y_pred_naive = naive.predict(x_test)
print("Naive Bayes")
print("Accuracy score =", accuracy_score(y_test, y_pred_naive))
print(metrics.classification_report(y_test, y_pred_naive ))

from sklearn.ensemble import GradientBoostingClassifier
gradient = GradientBoostingClassifier(n_estimators=100,max_depth=None,min_samples_split=2, random_state=0)
gradient.fit(x_train,y_train)
y_pred_gradient = gradient.predict(x_test)
print("Gradient Boosting")
print("Accuracy score =", accuracy_score(y_test, y_pred_gradient))
print(metrics.classification_report(y_test, y_pred_gradient ))

    
from sklearn.tree import DecisionTreeClassifier
decision = DecisionTreeClassifier()
decision.fit(x_train,y_train)
y_pred_decision = decision.predict(x_test)
print("Decision Tree")
print("Accuracy score =", accuracy_score(y_test, y_pred_decision))
print(metrics.classification_report(y_test, y_pred_decision ))

/usr/local/lib/python2.7/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

SVM
('Accuracy score =', 0.9418162044589451)
              precision    recall  f1-score   support

           0       0.94      1.00      0.97      1593
           1       0.97      0.58      0.73       246

   micro avg       0.94      0.94      0.94      1839
   macro avg       0.96      0.79      0.85      1839
weighted avg       0.94      0.94      0.94      1839

random
('Accuracy score =', 0.9651984774333877)
              precision    recall  f1-score   support

           0       0.97      0.99      0.98      1593
           1       0.93      0.80      0.86       246

   micro avg       0.97      0.97      0.97      1839
   macro avg       0.95      0.90      0.92      1839
weighted avg       0.96      0.97      0.96      1839

Logistic Regression
('Accuracy score =', 0.9477977161500816)
              precision    recall  f1-score   support

           0       0.96      0.98      0.97      1593
           1       0.88      0.71      0.78       246

   micro avg       0.95      0.95      0.95      1839
   macro avg       0.92      0.85      0.88      1839
weighted avg       0.95      0.95      0.95      1839

KNN
('Accuracy score =', 0.9429037520391517)
              precision    recall  f1-score   support

           0       0.96      0.98      0.97      1593
           1       0.82      0.73      0.77       246

   micro avg       0.94      0.94      0.94      1839
   macro avg       0.89      0.85      0.87      1839
weighted avg       0.94      0.94      0.94      1839

Naive Bayes
('Accuracy score =', 0.9336595976073954)
              precision    recall  f1-score   support

           0       0.96      0.96      0.96      1593
           1       0.75      0.76      0.76       246

   micro avg       0.93      0.93      0.93      1839
   macro avg       0.85      0.86      0.86      1839
weighted avg       0.93      0.93      0.93      1839

/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

Gradient Boosting
('Accuracy score =', 0.9526916802610114)
              precision    recall  f1-score   support

           0       0.97      0.98      0.97      1593
           1       0.84      0.79      0.82       246

   micro avg       0.95      0.95      0.95      1839
   macro avg       0.91      0.89      0.90      1839
weighted avg       0.95      0.95      0.95      1839

Decision Tree
('Accuracy score =', 0.9439912996193583)
              precision    recall  f1-score   support

           0       0.97      0.97      0.97      1593
           1       0.79      0.79      0.79       246

   micro avg       0.94      0.94      0.94      1839
   macro avg       0.88      0.88      0.88      1839
weighted avg       0.94      0.94      0.94      1839

In [ ]:
# data split into train and text
import numpy as np
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(features_array, label, test_size=0.33, random_state=42)

In [ ]:
x_train.shape

(3733, 12)

In [ ]:
data = pd.read_csv('SMSSpamCollection.csv', sep = '\t', names = ['label','message'])

In [ ]:
text = data['message']
class_label = data['label']

In [ ]:
import numpy as np
classes_list = ["ham","spam"]
label_index = class_label.apply(classes_list.index)
label = np.asarray(label_index)

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(text, label, test_size=0.33, random_state=42)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(ngram_range = (1,1))
x_train = vectorizer.fit_transform(X_train)
x_test = vectorizer.transform(X_test)

In [ ]:
x_train.shape

(3733, 7082)

In [ ]:
vectorizer.get_feature_names()

[u'00',
 u'000',
 u'000pes',
 u'0089',
 u'0121',
 u'01223585236',
 u'01223585334',
 u'02',
 u'0207',
 u'02072069400',
 u'02073162414',
 u'02085076972',
 u'021',
 u'03',
 u'04',
 u'0430',
 u'05',
 u'050703',
 u'0578',
 u'06',
 u'07',
 u'07008009200',
 u'07046744435',
 u'07090298926',
 u'07099833605',
 u'07123456789',
 u'0721072',
 u'07732584351',
 u'07734396839',
 u'07753741225',
 u'0776xxxxxxx',
 u'07781482378',
 u'07786200117',
 u'077xxx',
 u'07801543489',
 u'07808247860',
 u'07815296484',
 u'07821230901',
 u'07880867867',
 u'07946746291',
 u'0796xxxxxx',
 u'07973788240',
 u'07xxxxxxxxx',
 u'08',
 u'0800',
 u'08000407165',
 u'08000776320',
 u'08000839402',
 u'08000930705',
 u'08000938767',
 u'08001950382',
 u'08002888812',
 u'08002986030',
 u'08002986906',
 u'08002988890',
 u'08006344447',
 u'0808',
 u'08081263000',
 u'08081560665',
 u'0825',
 u'083',
 u'0844',
 u'08448350055',
 u'08448714184',
 u'0845',
 u'08450542832',
 u'08452810071',
 u'08452810073',
 u'08452810075over18',
 u'0870',
 u'08700435505150p',
 u'08700621170150p',
 u'08701213186',
 u'08701237397',
 u'08701417012',
 u'08701417012150p',
 u'0870141701216',
 u'0870241182716',
 u'08702490080',
 u'08702840625',
 u'08704050406',
 u'08704439680',
 u'08704439680ts',
 u'08706091795',
 u'0870737910216yrs',
 u'08707509020',
 u'08707808226',
 u'08708034412',
 u'08708800282',
 u'08709222922',
 u'08709501522',
 u'0871',
 u'087104711148',
 u'08712101358',
 u'0871212025016',
 u'08712300220',
 u'087123002209am',
 u'08712317606',
 u'08712400602450p',
 u'08712400603',
 u'08712402050',
 u'08712402578',
 u'08712402779',
 u'08712402902',
 u'08712402972',
 u'08712405020',
 u'08712405022',
 u'08712460324',
 u'0871277810710p',
 u'0871277810810',
 u'0871277810910p',
 u'08714342399',
 u'087147123779am',
 u'08714712379',
 u'08714712388',
 u'08714712394',
 u'08714712412',
 u'08715203028',
 u'08715203649',
 u'08715203656',
 u'08715203677',
 u'08715203694',
 u'08715205273',
 u'08715500022',
 u'08715705022',
 u'08717111821',
 u'0871750',
 u'08717507382',
 u'08717509990',
 u'08717895698',
 u'08717898035',
 u'08718711108',
 u'08718720201',
 u'08718723815',
 u'08718726270',
 u'087187262701',
 u'08718726970',
 u'08718726978',
 u'08718727870',
 u'08718730666',
 u'08718738001',
 u'08718738002',
 u'08718738034',
 u'08719181259',
 u'08719181503',
 u'08719181513',
 u'08719839835',
 u'08719899229',
 u'08719899230',
 u'09',
 u'09041940223',
 u'09050000301',
 u'09050000332',
 u'09050000555',
 u'09050000878',
 u'09050001295',
 u'09050001808',
 u'09050003091',
 u'09050090044',
 u'09056242159',
 u'09057039994',
 u'09058091854',
 u'09058091870',
 u'09058094455',
 u'09058094507',
 u'09058094565',
 u'09058094583',
 u'09058094594',
 u'09058094597',
 u'09058095107',
 u'09058095201',
 u'09058097189',
 u'09058097218',
 u'09058098002',
 u'09058099801',
 u'09061104276',
 u'09061104283',
 u'09061209465',
 u'09061213237',
 u'09061221061',
 u'09061221066',
 u'09061701444',
 u'09061743386',
 u'09061743806',
 u'09061743810',
 u'09061744553',
 u'09061749602',
 u'09061790121',
 u'09061790125',
 u'09061790126',
 u'09063440451',
 u'09063442151',
 u'09063458130',
 u'0906346330',
 u'09064011000',
 u'09064012160',
 u'09064017295',
 u'09064017305',
 u'09064018838',
 u'09064019014',
 u'09065069154',
 u'09065171142',
 u'09065174042',
 u'09065989180',
 u'09065989182',
 u'09066350750',
 u'09066358152',
 u'09066362206',
 u'09066362220',
 u'09066362231',
 u'09066364311',
 u'09066364349',
 u'09066364589',
 u'09066368470',
 u'09066382422',
 u'09066612661',
 u'09066649731from',
 u'09066660100',
 u'09071512433',
 u'09077818151',
 u'09090204448',
 u'09094646631',
 u'09094646899',
 u'09095350301',
 u'09096102316',
 u'09099725823',
 u'09099726395',
 u'09099726429',
 u'09099726481',
 u'09701213186',
 u'0a',
 u'10',
 u'100',
 u'1000',
 u'1000s',
 u'100p',
 u'100percent',
 u'100txt',
 u'1030',
 u'10am',
 u'10k',
 u'10p',
 u'10ppm',
 u'10th',
 u'11',
 u'1120',
 u'113',
 u'114',
 u'1146',
 u'116',
 u'1172',
 u'118p',
 u'11mths',
 u'11pm',
 u'12',
 u'1205',
 u'120p',
 u'121',
 u'125',
 u'1250',
 u'125gift',
 u'128',
 u'12hrs',
 u'12mths',
 u'13',
 u'130',
 u'1327',
 u'139',
 u'14',
 u'140',
 u'1405',
 u'145',
 u'146tf150p',
 u'14tcr',
 u'14thmarch',
 u'15',
 u'150',
 u'1500',
 u'150p',
 u'150p16',
 u'150pm',
 u'150ppermesssubscription',
 u'150ppm',
 u'150ppmsg',
 u'153',
 u'15541',
 u'16',
 u'165',
 u'1680',
 u'169',
 u'177',
 u'18',
 u'180',
 u'1843',
 u'18p',
 u'18yrs',
 u'195',
 u'1956669',
 u'1apple',
 u'1b6a5ecef91ff9',
 u'1cup',
 u'1da',
 u'1hr',
 u'1im',
 u'1lemon',
 u'1mega',
 u'1million',
 u'1st',
 u'1st4terms',
 u'1stchoice',
 u'1thing',
 u'1tulsi',
 u'1win150ppmx3',
 u'1winaweek',
 u'1winawk',
 u'1x150p',
 u'1yf',
 u'20',
 u'200',
 u'2000',
 u'2003',
 u'2004',
 u'2005',
 u'2007',
 u'2025050',
 u'20m12aq',
 u'20p',
 u'21',
 u'21870000',
 u'21st',
 u'22',
 u'220',
 u'220cm2',
 u'2309',
 u'23f',
 u'23g',
 u'24',
 u'24hrs',
 u'24m',
 u'24th',
 u'25',
 u'250',
 u'250k',
 u'255',
 u'25p',
 u'26',
 u'2667',
 u'26th',
 u'28',
 u'28days',
 u'28th',
 u'29',
 u'2b',
 u'2c',
 u'2channel',
 u'2day',
 u'2docd',
 u'2end',
 u'2ez',
 u'2find',
 u'2geva',
 u'2go',
 u'2gthr',
 u'2hook',
 u'2hrs',
 u'2i',
 u'2lands',
 u'2marrow',
 u'2moro',
 u'2morow',
 u'2morro',
 u'2morrow',
 u'2morrowxxxx',
 u'2mro',
 u'2mrw',
 u'2mwen',
 u'2nd',
 u'2nite',
 u'2optout',
 u'2p',
 u'2price',
 u'2rcv',
 u'2stop',
 u'2stoptx',
 u'2stoptxt',
 u'2u',
 u'2waxsto',
 u'2wt',
 u'2wu',
 u'2yr',
 u'2yrs',
 u'30',
 u'300',
 u'3000',
 u'300603',
 u'300p',
 u'3030',
 u'30apr',
 u'30ish',
 u'30pm',
 u'30pp',
 u'30s',
 u'31',
 u'3100',
 u'31p',
 u'32',
 u'32000',
 u'3230',
 u'326',
 u'33',
 u'330',
 u'350',
 u'3510i',
 u'3650',
 u'36504',
 u'3680',
 u'373',
 u'3750',
 u'37819',
 u'38',
 u'382',
 u'391784',
 u'3aj',
 u'3d',
 u'3g',
 u'3gbp',
 u'3hrs',
 u'3lions',
 u'3lp',
 u'3miles',
 u'3mins',
 u'3mobile',
 u'3optical',
 u'3pound',
 u'3qxj9',
 u'3rd',
 u'3ss',
 u'3uz',
 u'3xx',
 u'40',
 u'400',
 u'400mins',
 u'4041',
 u'40411',
 u'40533',
 u'40gb',
 u'41685',
 u'41782',
 u'42049',
 u'4217',
 u'42478',
 u'430',
 u'434',
 u'44',
 u'440',
 u'4403ldnw1a7rw18',
 u'447801259231',
 u'449050000301',
 u'449071512431',
 u'45',
 u'450',
 u'450ppw',
 u'45pm',
 u'47',
 u'4719',
 u'4742',
 u'47per',
 u'48',
 u'4882',
 u'48922',
 u'49',
 u'4a',
 u'4brekkie',
 u'4d',
 u'4eva',
 u'4fil',
 u'4get',
 u'4give',
 u'4goten',
 u'4info',
 u'4jx',
 u'4mths',
 u'4my',
 u'4qf2',
 u'4t',
 u'4th',
 u'4txt',
 u'4u',
 u'4ward',
 u'4wrd',
 u'4years',
 u'50',
 u'500',
 u'5000',
 u'505060',
 u'50gbp',
 u'50p',
 u'50perweeksub',
 u'50perwksub',
 u'50pm',
 u'50ppm',
 u'50rcvd',
 u'50s',
 u'515',
 u'523',
 u'5249',
 u'526',
 u'528',
 u'530',
 u'54',
 u'542',
 u'5digital',
 u'5free',
 u'5ish',
 u'5k',
 u'5min',
 u'5mls',
 u'5p',
 u'5pm',
 u'5th',
 u'5wb',
 u'5we',
 u'5wkg',
 u'600',
 u'6031',
 u'6089',
 u'60p',
 u'61',
 u'61200',
 u'61610',
 u'6230',
 u'62468',
 u'62735',
 u'630',
 u'65',
 u'650',
 u'66',
 u'6669',
 u'674',
 u'67441233',
 u'68866',
 u'69101',
 u'69696',
 u'69698',
 u'69866',
 u'69876',
 u'69888',
 u'69888nyt',
 u'69911',
 u'6days',
 u'6hl',
 u'6hrs',
 u'6ish',
 u'6missed',
 u'6months',
 u'6ph',
 u'6pm',
 u'6th',
 u'6times',
 u'6wu',
 u'6zf',
 u'700',
 u'71',
 u'7250',
 u'7250i',
 u'730',
 u'75',
 u'750',
 u'7548',
 u'75max',
 u'762',
 u'77',
 u'7732584351',
 u'78',
 u'786',
 u'7876150ppm',
 u'79',
 u'7am',
 u'7ish',
 u'7oz',
 u'7pm',
 u'7th',
 u'80',
 u'800',
 u'8000930705',
 u'80062',
 u'8007',
 u'80082',
 u'80122300p',
 u'80155',
 u'80182',
 u'80488',
 u'80608',
 u'80878',
 u'81010',
 u'81151',
 u'81303',
 u'81618',
 u'82050',
 u'820554ad0a1705572711',
 u'82242',
 u'82277',
 u'83021',
 u'83039',
 u'83049',
 u'83118',
 u'83222',
 u'83332',
 u'83338',
 u'83355',
 u'83370',
 u'83383',
 u'83435',
 u'83600',
 u'83738',
 u'84025',
 u'84122',
 u'84128',
 u'84199',
 u'84484',
 u'85',
 u'850',
 u'85023',
 u'85069',
 u'85233',
 u'8552',
 u'85555',
 u'86021',
 u'861',
 u'864233',
 u'86688',
 u'86888',
 u'87021',
 u'87066',
 u'87070',
 u'87077',
 u'87121',
 u'87131',
 u'872',
 u'87239',
 u'87575',
 u'88039',
 u'88066',
 u'88088',
 u'88222',
 u'88600',
 u'88800',
 u'8883',
 u'88877',
 u'88888',
 u'89034',
 u'89070',
 u'89080',
 u'89105',
 u'89123',
 u'89545',
 u'89555',
 u'89693',
 u'8am',
 u'8ball',
 u'8lb',
 u'8p',
 u'8pm',
 u'8th',
 u'8wp',
 u'900',
 u'9061100010',
 u'910',
 u'9280114',
 u'92h',
 u'9307622',
 u'945',
 u'946',
 u'95',
 u'9755',
 u'98321561',
 u'99',
 u'9996',
 u'9ae',
 u'9am',
 u'9ja',
 u'9pm',
 u'9t',
 u'9th',
 u'____',
 u'a21',
 u'a30',
 u'aah',
 u'aaniye',
 u'aaooooright',
 u'aathi',
 u'abbey',
 u'abi',
 u'ability',
 u'abiola',
 u'abj',
 u'able',
 u'abnormally',
 u'about',
 u'aboutas',
 u'above',
 u'abroad',
 u'absence',
 u'absolutly',
 u'abt',
 u'abta',
 u'aburo',
 u'abuse',
 u'abusers',
 u'ac',
 u'academic',
 u'acc',
 u'accent',
 u'accept',
 u'access',
 u'accessible',
 u'accidant',
 u'accident',
 u'accidentally',
 u'accommodation',
 u'accommodationvouchers',
 u'accomodations',
 u'accordingly',
 u'account',
 u'accounts',
 u'accumulation',
 u'achan',
 u'ache',
 u'acid',
 u'acl03530150pm',
 u'acnt',
 u'aco',
 u'across',
 u'act',
 u'acted',
 u'acting',
 u'action',
 u'activ8',
 u'activate',
 u'active',
 u'activities',
 u'actor',
 u'actual',
 u'actually',
 u'ad',
 u'adam',
 u'add',
 u'addamsfa',
 u'added',
 u'addicted',
 u'addie',
 u'adding',
 u'address',
 u'adewale',
 u'adjustable',
 u'admin',
 u'administrator',
 u'admirer',
 u'admission',
 u'adore',
 u'adoring',
 u'adress',
 u'adrian',
 u'ads',
 u'adsense',
 u'adult',
 u'adults',
 u'advance',
 u'adventure',
 u'adventuring',
 u'advice',
 u'advise',
 u'advising',
 u'afew',
 u'affairs',
 u'affection',
 u'affectionate',
 u'afford',
 u'afghanistan',
 u'afraid',
 u'africa',
 u'aft',
 u'after',
 u'afternon',
 u'afternoon',
 u'aftr',
 u'ag',
 u'again',
 u'against',
 u'agalla',
 u'age',
 u'age16',
 u'age23',
 u'agent',
 u'ages',
 u'agidhane',
 u'ago',
 u'agree',
 u'ah',
 u'aha',
 u'ahead',
 u'ahhhh',
 u'ahmad',
 u'ahold',
 u'aid',
 u'aids',
 u'aight',
 u'ain',
 u'aint',
 u'air',
 u'airport',
 u'airtel',
 u'aiya',
 u'aiyah',
 u'aiyar',
 u'aiyo',
 u'ajith',
 u'aka',
 u'akon',
 u'al',
 u'alaikkum',
 u'albi',
 u'album',
 u'alcohol',
 u'alert',
 u'alerts',
 u'alex',
 u'alfie',
 u'algorithms',
 u'ali',
 u'alian',
 u'alibi',
 u'alive',
 u'all',
 u'allah',
 u'allalo',
 u'allday',
 u'alle',
 u'allo',
 u'allow',
 u'allowed',
 u'allows',
 u'almost',
 u'alone',
 u'along',
 u'alot',
 u'already',
 u'alright',
 u'alrite',
 u'also',
 u'although',
 u'aluable',
 u'always',
 u'alwys',
 u'am',
 u'amanda',
 u'amazing',
 u'ambitious',
 u'ambrith',
 u'american',
 u'ami',
 u'amigos',
 u'amma',
 u'ammae',
 u'amnow',
 u'among',
 u'amongst',
 u'amore',
 u'amount',
 u'amp',
 u'amrca',
 u'amrita',
 u'ams',
 u'amt',
 u'amy',
 u'an',
 u'ana',
 u'analysis',
 u'and',
 u'anderson',
 u'andre',
 u'andrews',
 u'angry',
 u'animal',
 u'animation',
 u'anjola',
 u'annie',
 u'anniversary',
 u'annoncement',
 u'announced',
 u'announcement',
 u'annoyin',
 u'anonymous',
 u'anot',
 u'another',
 u'ans',
 u'ansr',
 u'answer',
 u'answered',
 u'answerin',
 u'answering',
 u'answers',
 u'answr',
 u'antelope',
 u'antha',
 u'anthony',
 u'anti',
 u'any',
 u'anybody',
 u'anyhow',
 u'anymore',
 u'anyone',
 u'anyones',
 u'anyplaces',
 u'anythiing',
 u'anythin',
 u'anything',
 u'anythingtomorrow',
 u'anytime',
 u'anyway',
 u'anyways',
 u'anywhere',
 u'apart',
 u'apartment',
 u'apes',
 u'apeshit',
 u'apo',
 u'apologise',
 u'apology',
 u'app',
 u'apparently',
 u'appeal',
 u'appear',
 u'applausestore',
 u'applebees',
 u'application',
 u'apply',
 u'applyed',
 u'applying',
 u'appointment',
 u'appointments',
 u'appreciate',
 u'appreciated',
 u'approve',
 u'approved',
 u'approx',
 u'apps',
 u'appt',
 u'appy',
 u'april',
 u'aproach',
 u'aquarius',
 u'ar',
 u'arab',
 u'arabian',
 u'arcade',
 u'ard',
 u'are',
 u'area',
 u'aren',
 u'arestaurant',
 u'aretaking',
 u'argentina',
 u'argh',
 u'argue',
 u'argument',
 u'arises',
 u'arm',
 u'armand',
 u'arms',
 u'arng',
 u'arngd',
 u'arnt',
 u'around',
 u'arrange',
 u'arranging',
 u'arrested',
 u'arrival',
 u'arrive',
 u'arsenal',
 u'art',
 u'artists',
 u'arts',
 u'arty',
 u'arul',
 u'arun',
 u'as',
 u'asa',
 u'asap',
 u'asda',
 u'ashley',
 u'ashwini',
 u'asian',
 u'asjesus',
 u'ask',
 u'askd',
 u'asked',
 u'askin',
 u'asking',
 u'asks',
 ...]

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn import metrics

from sklearn.svm import SVC
model_SVM = SVC()
model_SVM.fit(x_train, y_train)
y_pred_SVM = model_SVM.predict(x_test)
print("SVM")
print("Accuracy score =", accuracy_score(y_test, y_pred_SVM))
print(metrics.classification_report(y_test, y_pred_SVM))

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100,max_depth=None,min_samples_split=2, random_state=0)
rf.fit(x_train,y_train)
y_pred_rf = rf.predict(x_test)
print("random")
print("Accuracy score =", accuracy_score(y_test, y_pred_rf))
print(metrics.classification_report(y_test, y_pred_rf))

from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
LR.fit(x_train,y_train)
y_pred_LR = LR.predict(x_test)
print("Logistic Regression")
print("Accuracy score =", accuracy_score(y_test, y_pred_LR))
print(metrics.classification_report(y_test, y_pred_LR ))

from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors = 5)
neigh.fit(x_train,y_train)
y_pred_KNN = neigh.predict(x_test)
print("KNN")
print("Accuracy score =", accuracy_score(y_test, y_pred_KNN))
print(metrics.classification_report(y_test, y_pred_KNN ))

from sklearn.naive_bayes import GaussianNB
naive = GaussianNB()
naive.fit(x_train.toarray(),y_train)
y_pred_naive = naive.predict(x_test.toarray())
print("Naive Bayes")
print("Accuracy score =", accuracy_score(y_test, y_pred_naive))
print(metrics.classification_report(y_test, y_pred_naive ))

from sklearn.ensemble import GradientBoostingClassifier
gradient = GradientBoostingClassifier(n_estimators=100,max_depth=None,min_samples_split=2, random_state=0)
gradient.fit(x_train,y_train)
y_pred_gradient = gradient.predict(x_test)
print("Gradient Boosting")
print("Accuracy score =", accuracy_score(y_test, y_pred_gradient))
print(metrics.classification_report(y_test, y_pred_gradient ))

    
from sklearn.tree import DecisionTreeClassifier
decision = DecisionTreeClassifier()
decision.fit(x_train,y_train)
y_pred_decision = decision.predict(x_test)
print("Decision Tree")
print("Accuracy score =", accuracy_score(y_test, y_pred_decision))
print(metrics.classification_report(y_test, y_pred_decision ))

SVM
('Accuracy score =', 0.866231647634584)
              precision    recall  f1-score   support

           0       0.87      1.00      0.93      1593
           1       0.00      0.00      0.00       246

   micro avg       0.87      0.87      0.87      1839
   macro avg       0.43      0.50      0.46      1839
weighted avg       0.75      0.87      0.80      1839

/usr/local/lib/python2.7/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

random
('Accuracy score =', 0.9804241435562806)
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1593
           1       1.00      0.85      0.92       246

   micro avg       0.98      0.98      0.98      1839
   macro avg       0.99      0.93      0.95      1839
weighted avg       0.98      0.98      0.98      1839

Logistic Regression
('Accuracy score =', 0.9717237629146275)
              precision    recall  f1-score   support

           0       0.97      1.00      0.98      1593
           1       0.99      0.80      0.88       246

   micro avg       0.97      0.97      0.97      1839
   macro avg       0.98      0.90      0.93      1839
weighted avg       0.97      0.97      0.97      1839

KNN
('Accuracy score =', 0.9037520391517129)
              precision    recall  f1-score   support

           0       0.90      1.00      0.95      1593
           1       1.00      0.28      0.44       246

   micro avg       0.90      0.90      0.90      1839
   macro avg       0.95      0.64      0.69      1839
weighted avg       0.91      0.90      0.88      1839

Naive Bayes
('Accuracy score =', 0.9059271343121261)
              precision    recall  f1-score   support

           0       0.98      0.91      0.94      1593
           1       0.60      0.91      0.72       246

   micro avg       0.91      0.91      0.91      1839
   macro avg       0.79      0.91      0.83      1839
weighted avg       0.93      0.91      0.91      1839

Gradient Boosting
('Accuracy score =', 0.9733550842849374)
              precision    recall  f1-score   support

           0       0.98      0.99      0.98      1593
           1       0.93      0.86      0.90       246

   micro avg       0.97      0.97      0.97      1839
   macro avg       0.96      0.93      0.94      1839
weighted avg       0.97      0.97      0.97      1839

Decision Tree
('Accuracy score =', 0.9684611201740077)
              precision    recall  f1-score   support

           0       0.98      0.99      0.98      1593
           1       0.90      0.86      0.88       246

   micro avg       0.97      0.97      0.97      1839
   macro avg       0.94      0.92      0.93      1839
weighted avg       0.97      0.97      0.97      1839